[package]
name = "ohua-runtime-tests"
version = "0.1.0"
authors = ["Felix Wittwer <dev@felixwittwer.de>"]

[dependencies]
ohua_codegen = { path = "../ohua_codegen", features = ["debug"] }
ohua_runtime = { path = "../ohua_runtime" }
