[package]
name = "mainarg_reuse_across_ops"
version = "0.1.0"
authors = ["Felix Wittwer <dev@felixwittwer.de>"]

[dependencies]
ohua_codegen = { path = "../../ohua_codegen" }
ohua_runtime = { path = "../../ohua_runtime" }
